name: HegeWorld
version: '${project.version}'
main: com.hegemonstudio.hegeworld.HegeWorldPlugin
api-version: '1.20'
depend:
  - ImpactLib
  - WorldEdit
permissions:
  hegeworld.block.admin:
    default: op
  hegeworld.cmd.give:
    default: op